name: HEXO自动部署

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: 使用 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 配置环境
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "${{secrets.GITNAME}}"
          git config --global user.email "${{secrets.GITME}}"
      - name: 安装依赖项
        run: |
          npm i -g hexo-cli
          npm i
          npm install --save hexo-tag-aplayer
          npm install hexo-renderer-pug hexo-renderer-stylus --save
          npm install hexo-generator-search --save
          npm install hexo-filter-nofollow --save
          npm install hexo-abbrlink --save
      - name: 部署 hexo
        run: |
          hexo clean && hexo generate && hexo deploy
